version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.3
    environment:
      - JEKYLL_ENV=development
    ports:
      - '4000:4000'
    command: jekyll serve
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
